// Comprehensive list of known disposable/temporary email domains.
// This blocks users from submitting the contact form with throwaway emails.
// Sources: aggregated from multiple public disposable email lists.

const disposableDomains = new Set([
  // Most popular temp mail services
  'tempmail.com',
  'temp-mail.org',
  'temp-mail.io',
  'tempail.com',
  'tempr.email',
  'tempmailo.com',
  'tmpmail.net',
  'tmpmail.org',
  'temp-mail.de',
  'temp-mail.ru',

  // Guerrilla Mail
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.info',
  'guerrillamailblock.com',
  'grr.la',
  'sharklasers.com',
  'guerrilla.ml',

  // Mailinator family
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'maildrop.cc',

  // 10MinuteMail & variants
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '10minutemail.de',
  '10minute.email',
  '10mail.org',
  '10mail.net',

  // YOPmail
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yopmail.gq',

  // Throwaway / trash mail
  'throwaway.email',
  'throwawaymail.com',
  'trashmail.com',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.io',
  'trashemail.de',
  'trashymail.com',
  'trashymail.net',

  // Fake mail / temp inbox
  'fakeinbox.com',
  'fakemail.net',
  'fakemailgenerator.com',
  'fakemail.fr',

  // Dispostable
  'dispostable.com',

  // Getnada
  'getnada.com',
  'nada.email',
  'nada.ltd',

  // Mohmal
  'mohmal.com',
  'mohmal.im',
  'mohmal.in',
  'mohmal.tech',

  // Burner mail
  'burnermail.io',
  'burnmail.com',

  // Crazymailing
  'crazymailing.com',

  // MailDrop
  'maildrop.cc',
  'maildrop.cf',
  'maildrop.ga',
  'maildrop.gq',
  'maildrop.ml',

  // Harakiri Mail
  'harakirimail.com',

  // Discard email
  'discardmail.com',
  'discardmail.de',

  // Mailnesia
  'mailnesia.com',

  // MyTemp
  'mytemp.email',
  'mytempemail.com',

  // TempInbox
  'tempinbox.com',
  'tempinbox.co.uk',

  // SpamGourmet
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',

  // Mailcatch
  'mailcatch.com',

  // Mintemail
  'mintemail.com',

  // Inboxkitten
  'inboxkitten.com',

  // EmailOnDeck
  'emailondeck.com',

  // Mohmal variants
  'emailfake.com',

  // MailSac
  'mailsac.com',

  // Temp mail services
  'tempail.com',
  'tempmailaddress.com',
  'tempmails.net',

  // Disposable domains
  'disposableemailaddresses.emailmiser.com',
  'disposable-email.ml',
  'disposable.email',
  'disposableaddress.com',

  // More popular services
  'getairmail.com',
  'mailforspam.com',
  'safetymail.info',
  'filzmail.com',
  'mailexpire.com',
  'tempsky.com',
  'tempomail.fr',
  'disbox.net',
  'disbox.org',
  'mailnull.com',
  'spamfree24.org',
  'mytrashmail.com',
  'thankyou2010.com',
  'mailzilla.com',
  'mail-temporaire.fr',
  'jetable.fr.nf',
  'jetable.net',
  'jetable.org',

  // Russian temp mail services
  'mailfa.tk',
  'mail1a.de',
  'cuvox.de',
  'armyspy.com',
  'dayrep.com',
  'einrot.com',
  'fleckens.hu',
  'gustr.com',
  'jourrapide.com',
  'rhyta.com',
  'superrito.com',
  'teleworm.us',

  // Indian temp mail services
  'tempmaili.com',

  // Misc popular
  'mailseal.de',
  'mail.tm',
  'internxt.com',
  'emailnax.com',
  'tmail.ws',
  'tmpbox.net',
  'luxusmail.org',
  'binkmail.com',
  'bobmail.info',
  'chammy.info',
  'devnullmail.com',
  'dingbone.com',
  'dontreg.com',
  'e4ward.com',
  'emailgo.de',
  'emailisvalid.com',
  'emailsensei.com',
  'emailtemporario.com.br',
  'ephemail.net',
  'explodemail.com',
  'fastacura.com',
  'filzmail.com',
  'fixmail.tk',
  'get1mail.com',
  'getonemail.com',
  'getonemail.net',
  'girlsundertheinfluence.com',
  'givmail.com',
  'gishpuppy.com',
  'great-host.in',
  'greensloth.com',
  'haltospam.com',
  'hotpop.com',
  'ichimail.com',
  'imails.info',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'insorg-mail.info',
  'ipoo.org',
  'irish2me.com',
  'jetable.com',
  'kasmail.com',
  'koszmail.pl',
  'kurzepost.de',
  'lawlita.com',
  'letthemeatspam.com',
  'lhsdv.com',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'lol.ovpn.to',
  'lookugly.com',
  'lopl.co.cc',
  'lortemail.dk',
  'lovemeleaveme.com',
  'lr78.com',
  'maileater.com',
  'mailexpire.com',
  'mailfreeonline.com',
  'mailguard.me',
  'mailin8r.com',
  'mailincubator.com',
  'mailme.ir',
  'mailme.lv',
  'mailmetrash.com',
  'mailmoat.com',
  'mailquack.com',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailslite.com',
  'mailtemp.info',
  'mailtothis.com',
  'mailtrash.net',
  'mailzilla.org',
  'makemetheking.com',
  'manifestgenerator.com',
  'messagebeamer.de',
  'mezimages.net',
  'mfsa.ru',
  'mfsa.info',
  'mt2015.com',
  'mx0.wwwnew.eu',
  'mycleaninbox.net',
  'mypartyclip.de',
  'myphantom.com',
  'mysamp.de',
  'myspaceinc.com',
  'myspaceinc.net',
  'myspaceinc.org',
  'myspacepimpedup.com',
  'mytrashmail.com',
  'neomailbox.com',
  'nepwk.com',
  'nervmich.net',
  'nervtansen.de',
  'netmails.com',
  'netmails.net',
  'neverbox.com',
  'no-spam.ws',
  'nobulk.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.xl.cx',
  'nomail2me.com',
  'nomorespamemails.com',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospammail.net',
  'nothingtoseehere.ca',
  'nowmymail.com',
  'nurfuerspam.de',
  'nus.edu.sg',
  'nwldx.com',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'oneoffemail.com',
  'onewaymail.com',
  'oopi.org',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pimpedupmyspace.com',
  'pjjkp.com',
  'plexolan.de',
  'pookmail.com',
  'privacy.net',
  'privatdemail.net',
  'proxymail.eu',
  'prtnx.com',
  'putthisinyouremail.com',
  'qq.com',
  'quickinbox.com',
  'rcpt.at',
  'reallymymail.com',
  'receiveee.com',
  'regbypass.com',
  'rejectmail.com',
  'rklips.com',
  'rmqkr.net',
  'royal.net',
  'rppkn.com',
  'rtrtr.com',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'scatmail.com',
  'schafmail.de',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'shiftmail.com',
  'shitmail.me',
  'shortmail.net',
  'sibmail.com',
  'skeefmail.com',
  'slaskpost.se',
  'slipry.net',
  'slopsbox.com',
  'smashmail.de',
  'snoopmail.info',
  'sofimail.com',
  'sofort-mail.de',
  'softpls.asia',
  'sogetthis.com',
  'soodonims.com',
  'spam.la',
  'spam.su',
  'spam4.me',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambox.info',
  'spambox.irishspringrealty.com',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfighter.cf',
  'spamfighter.ga',
  'spamfighter.gq',
  'spamfighter.ml',
  'spamfighter.tk',
  'spamfree.eu',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamtrap.ro',
  'spamtrail.com',
  'spamwc.de',
  'speed.1s.fr',
  'spoofmail.de',
  'stuffmail.de',
  'supergreatmail.com',
  'supermailer.jp',
  'suremail.info',
  'svk.jp',
  'sweetxxx.de',
  'tafmail.com',
  'tafoi.gr',
  'tagmymedia.com',
  'tagyoureit.com',
  'talkinator.com',
  'tapchicuoihoi.com',
  'teewars.org',
  'teleworm.com',
  'tempalias.com',
  'tempe4mail.com',
  'tempemail.biz',
  'tempemail.co.za',
  'tempemail.com',
  'tempemail.net',
  'tempemails.io',
  'tempinbox.com',
  'tempmail.eu',
  'tempmail.it',
  'tempmail2.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'thanksnospam.info',
  'thankyou2010.com',
  'thisisnotmyrealemail.com',
  'throwawayemailaddress.com',
  'tittbit.in',
  'tizi.com',
  'tmailinator.com',
  'toiea.com',
  'toomail.biz',
  'topranklist.de',
  'tormail.net',
  'tormail.org',
  'tradermail.info',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'umail.net',
  'upliftnow.com',
  'uplipht.com',
  'venompen.com',
  'veryreallyme.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'vomoto.com',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'wasteland.rfc822.org',
  'webemail.me',
  'weg-werf-email.de',
  'wegwerfadresse.de',
  'wegwerfemail.com',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.info',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wetrainbayarea.com',
  'wetrainbayarea.org',
  'wh4f.org',
  'whatiaas.com',
  'whatpaas.com',
  'whyspam.me',
  'wikidocuslice.com',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'wuzup.net',
  'wuzupmail.net',
  'wwwnew.eu',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xjoi.com',
  'xmaily.com',
  'xoxy.net',
  'yep.it',
  'yogamaven.com',
  'yomail.info',
  'yuurok.com',
  'zehnminuten.de',
  'zehnminutenmail.de',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.org',

  // Additional commonly used ones
  'mailpoof.com',
  'tempemailfree.com',
  'emkei.cz',
  'dropmail.me',
  'mailhero.io',
  'emailfake.com',
  'email-fake.com',
  'crazymailing.com',
  'smailpro.com',
  'tempm.com',
  'emailondeck.com',
  'tempmail.plus',
  'tempmail.ninja',
  'tmail.ws',
  'mail.tm',
  'etempmail.com',
  'cs.email',
  'inboxes.com',
  'mailgw.com',
  'mailtrap.io',
  'mailsac.com',
  'testmail.app',
]);

/**
 * Check if an email domain is a known disposable/temporary email service.
 * @param {string} email - The email address to check.
 * @returns {boolean} - True if disposable, false if legitimate.
 */
export function isDisposableEmail(email) {
  if (!email || typeof email !== 'string') return false;
  const domain = email.trim().toLowerCase().split('@')[1];
  if (!domain) return false;
  return disposableDomains.has(domain);
}

export default disposableDomains;
